version: '3.1'

services:

  db:
    image: postgres
    ports:
      - 5434:5432
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bikeramp-db
    volumes:
      - "./db-data:/var/lib/postgresql/data"
    networks:
      - network
volumes:
    db-data:
      driver: local
networks:
  network:
